In [1]:
import numpy as np


In [9]:
#create array , matrix
a = np.array([1,2,3,4])


In [3]:
a

array([1, 2, 3, 4, 5])

In [4]:
b=np.array([[1,2,3],[4,5,6],[7,8,9]])

b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
#shape
print(b.shape, a.shape)

(3, 3) (5,)


In [8]:
#reshape
c = a.reshape((5,1))
c.shape


(5, 1)

In [13]:
d = a.reshape((2,-1,1))

In [14]:
d.shape

(2, 2, 1)

In [15]:
#concatinate
a = np.array([1,2,3])
b = np.array([4,5,6])
c =np.concatenate((a,b))
c

array([1, 2, 3, 4, 5, 6])

In [18]:
a = np.array([1,2])
b = np.array([5,6])
c = a*b
c

array([ 5, 12])

In [19]:
c =np.array([10])
d =a+c
d

array([11, 12])

In [20]:
a= np.array([1, 2, 3, 4, 6, 7, 8, 9])
a.shape


(8,)

In [22]:
b= a[2:7:2]
b

array([3, 6, 8])

In [23]:
c = a[a>3]
c

array([4, 6, 7, 8, 9])

In [24]:
a

array([1, 2, 3, 4, 6, 7, 8, 9])

In [25]:
sum_a =np.sum(a)
sum_a

np.int64(40)

In [26]:
max_a =np.max(a)
max_a   

np.int64(9)

In [27]:
min_a =np.min(a)
min_a   

np.int64(1)

In [28]:
a = np.array([1, 4, 2, 5, 3])
b = np.sort(a)
b

array([1, 2, 3, 4, 5])

In [29]:
a = np.random.randint(0,10, size=(3,4))
a

array([[0, 4, 9, 6],
       [8, 8, 2, 8],
       [1, 9, 3, 0]], dtype=int32)

In [30]:
a = np.array([[1,2,3]])
b = np.array([[9,8,7]])
c=np.vstack((a,b))
c

array([[1, 2, 3],
       [9, 8, 7]])

In [31]:
#normalize
mean_a =np.mean(a)
mean_a


np.float64(2.0)

In [32]:
std_a =np.std(a)
std_a

np.float64(0.816496580927726)

In [33]:
norm_a = (a - mean_a) / std_a
norm_a

array([[-1.22474487,  0.        ,  1.22474487]])