In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df =pd.read_csv('diabets.csv')
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,Age,Outcome
0,2,135,80,33,155,27.1,29,1
1,0,89,66,23,94,28.1,21,0
2,1,118,72,35,120,34.9,25,0
3,3,145,82,30,110,32.5,31,1
4,5,160,74,28,135,34.2,45,1


In [ ]:
df.shape

(37, 8)

In [ ]:
df['Outcome'].value_counts()

Outcome
0    19
1    18
Name: count, dtype: int64

In [ ]:
x =df.drop('Outcome', axis=1)
y =df['Outcome']

In [ ]:
x

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,Age
0,2,135,80,33,155,27.1,29
1,0,89,66,23,94,28.1,21
2,1,118,72,35,120,34.9,25
3,3,145,82,30,110,32.5,31
4,5,160,74,28,135,34.2,45
5,0,95,70,20,80,26.5,22
6,2,125,68,32,105,30.1,27
7,4,150,78,29,140,33.0,34
8,1,130,60,22,85,28.4,23
9,3,140,75,31,130,32.8,30


In [ ]:
y

0     1
1     0
2     0
3     1
4     1
5     0
6     0
7     1
8     0
9     1
10    0
11    1
12    0
13    1
14    0
15    1
16    0
17    1
18    0
19    1
20    0
21    0
22    1
23    1
24    0
25    1
26    0
27    1
28    1
29    0
30    0
31    1
32    0
33    1
34    0
35    0
36    1
Name: Outcome, dtype: int64

In [ ]:
x =np.array(x)
y =np.array(y)

In [ ]:
x

array([[  2. , 135. ,  80. ,  33. , 155. ,  27.1,  29. ],
       [  0. ,  89. ,  66. ,  23. ,  94. ,  28.1,  21. ],
       [  1. , 118. ,  72. ,  35. , 120. ,  34.9,  25. ],
       [  3. , 145. ,  82. ,  30. , 110. ,  32.5,  31. ],
       [  5. , 160. ,  74. ,  28. , 135. ,  34.2,  45. ],
       [  0. ,  95. ,  70. ,  20. ,  80. ,  26.5,  22. ],
       [  2. , 125. ,  68. ,  32. , 105. ,  30.1,  27. ],
       [  4. , 150. ,  78. ,  29. , 140. ,  33. ,  34. ],
       [  1. , 130. ,  60. ,  22. ,  85. ,  28.4,  23. ],
       [  3. , 140. ,  75. ,  31. , 130. ,  32.8,  30. ],
       [  0. ,  99. ,  64. ,  19. ,  70. ,  25.5,  20. ],
       [  2. , 155. ,  82. ,  37. , 150. ,  36.5,  33. ],
       [  1. , 110. ,  68. ,  24. ,  90. ,  27.8,  24. ],
       [  5. , 170. ,  80. ,  38. , 160. ,  37.9,  42. ],
       [  0. ,  92. ,  65. ,  21. ,  75. ,  26. ,  19. ],
       [  3. , 148. ,  76. ,  28. , 120. ,  31.5,  29. ],
       [  2. , 138. ,  74. ,  30. , 115. ,  29.8,  32. ],
       [  4. ,

In [ ]:
y

array([1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0,
       1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1])

In [ ]:
#normalization
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x =scaler.fit_transform(x)
x

array([[-0.10226943,  0.11415571,  0.97462431,  0.82537028,  1.40289605,
        -1.07494064, -0.13881943],
       [-1.36359234, -1.86842609, -1.16459346, -1.01431046, -0.82221736,
        -0.80961173, -1.24937484],
       [-0.73293088, -0.61853757, -0.24778584,  1.19330642,  0.12619163,
         0.99462486, -0.69409714],
       [ 0.52839203,  0.54515175,  1.28022685,  0.27346606, -0.23858106,
         0.35783548,  0.13881943],
       [ 1.78971495,  1.19164582,  0.0578167 , -0.09447009,  0.67335067,
         0.80889462,  2.08229141],
       [-1.36359234, -1.60982847, -0.55338838, -1.56621468, -1.33289913,
        -1.23413799, -1.11055542],
       [-0.10226943, -0.31684033, -0.85899092,  0.6414022 , -0.4209674 ,
        -0.27895391, -0.41645828],
       [ 1.15905349,  0.76064977,  0.66902177,  0.08949798,  0.85573701,
         0.49049993,  0.55527771],
       [-0.73293088, -0.10134231, -2.08140108, -1.19827853, -1.15051278,
        -0.73001306, -0.97173599],
       [ 0.52839203,  0.3296

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test =train_test_split(x, y, test_size=0.2, random_state=42)

In [ ]:
x_train.shape, y_train.shape

((29, 7), (29,))

In [ ]:
x_test.shape, y_test.shape

((8, 7), (8,))